# Generated by Django 5.2.3 on 2025-08-02 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_2fa',
        ),
    ]
