# Generated by Django 5.2.1 on 2025-06-17 16:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainState',
            fields=[
                ('blockchain', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Blockchain/Network')),
                ('last_processed_block', models.BigIntegerField(default=0, verbose_name='Last Processed Block')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blockchain Scanner State',
                'verbose_name_plural': 'Blockchain Scanner States',
            },
        ),
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('symbol', models.CharField(max_length=20, unique=True, verbose_name='Symbol')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='crypto_icons/', verbose_name='Icon')),
                ('currency_type', models.CharField(choices=[('fiat', 'Fiat'), ('crypto', 'Cryptocurrency')], default='crypto', max_length=10, verbose_name='Currency Type')),
                ('network', models.CharField(blank=True, max_length=50, null=True, verbose_name='Network')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('coingecko_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='CoinGecko ID')),
                ('contract_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Contract Address')),
                ('decimals', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Decimals')),
                ('min_exchange_amount', models.DecimalField(decimal_places=8, default=Decimal('0.0001'), max_digits=18, verbose_name='Min Exchange Amount')),
                ('max_exchange_amount', models.DecimalField(decimal_places=8, default=Decimal('10.0'), max_digits=18, verbose_name='Max Exchange Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'currency',
                'verbose_name_plural': 'currencies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CryptoPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_usd', models.DecimalField(decimal_places=8, max_digits=18)),
                ('price_btc', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('price_eth', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('volume_24h', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='crypto.cryptocurrency')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Interest Rate (%)')),
                ('duration_value', models.PositiveIntegerField(default=1, verbose_name='Duration Value')),
                ('duration_unit', models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], default='month', max_length=10, verbose_name='Duration Unit')),
                ('min_investment', models.DecimalField(decimal_places=8, max_digits=18, verbose_name='Minimum Investment')),
                ('max_investment', models.DecimalField(decimal_places=8, max_digits=18, verbose_name='Maximum Investment')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('early_withdrawal_allowed', models.BooleanField(default=False, verbose_name='Early Withdrawal Allowed')),
                ('early_withdrawal_fee', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Early Withdrawal Fee (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_plans', to='crypto.cryptocurrency')),
            ],
            options={
                'verbose_name': 'investment plan',
                'verbose_name_plural': 'investment plans',
            },
        ),
        migrations.CreateModel(
            name='UserDepositMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=50, verbose_name='Network')),
                ('memo', models.CharField(max_length=128, unique=True, verbose_name='Memo/Destination Tag')),
                ('status', models.CharField(choices=[('waiting', 'Waiting for deposit'), ('used', 'Used'), ('expired', 'Expired')], db_index=True, default='waiting', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto.cryptocurrency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_memos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Deposit Memo',
                'verbose_name_plural': 'User Deposit Memos',
            },
        ),
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=24, verbose_name='Total Balance')),
                ('available_balance', models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=24, verbose_name='Available Balance')),
                ('locked_balance', models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=24, verbose_name='Locked Balance')),
                ('is_system_wallet', models.BooleanField(default=False, verbose_name='System Wallet')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto.cryptocurrency', verbose_name='Currency')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'wallet',
                'verbose_name_plural': 'wallets',
                'unique_together': {('user', 'currency', 'is_system_wallet')},
            },
        ),
        migrations.CreateModel(
            name='UserInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=24, verbose_name='Investment Amount')),
                ('expected_return', models.DecimalField(decimal_places=8, max_digits=24, verbose_name='Expected Return')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('withdrawn', 'Withdrawn Early')], default='active', max_length=20, verbose_name='Status')),
                ('actual_return', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True, verbose_name='Actual Return')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='Completion Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_investments', to='crypto.investmentplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='crypto.userwallet')),
            ],
            options={
                'verbose_name': 'user investment',
                'verbose_name_plural': 'user investments',
            },
        ),
        migrations.CreateModel(
            name='ExchangePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('custom_fee_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('min_from_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('max_from_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_pairs', to='crypto.cryptocurrency')),
                ('to_crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_pairs', to='crypto.cryptocurrency')),
            ],
            options={
                'verbose_name': 'exchange pair',
                'verbose_name_plural': 'exchange pairs',
                'unique_together': {('from_crypto', 'to_crypto')},
            },
        ),
        migrations.CreateModel(
            name='SystemWalletAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=50, verbose_name='Network')),
                ('address', models.CharField(max_length=255, unique=True, verbose_name='Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_addresses', to='crypto.cryptocurrency')),
            ],
            options={
                'verbose_name': 'System Wallet Address',
                'verbose_name_plural': 'System Wallet Addresses',
                'unique_together': {('currency', 'network')},
            },
        ),
    ]
