# Generated by Django 5.0.6 on 2025-04-23 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=20)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='crypto_icons/')),
                ('is_active', models.BooleanField(default=True)),
                ('coingecko_id', models.CharField(blank=True, max_length=100, null=True)),
                ('api_id', models.CharField(blank=True, max_length=100, null=True)),
                ('min_amount', models.DecimalField(decimal_places=8, default=0.0001, max_digits=18)),
                ('max_amount', models.DecimalField(decimal_places=8, default=10, max_digits=18)),
                ('fee_percentage', models.DecimalField(decimal_places=2, default=0.5, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'cryptocurrency',
                'verbose_name_plural': 'cryptocurrencies',
            },
        ),
        migrations.CreateModel(
            name='CryptoPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_usd', models.DecimalField(decimal_places=8, max_digits=18)),
                ('price_btc', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('price_eth', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('volume_24h', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='crypto.cryptocurrency')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ExchangePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('custom_fee_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('min_from_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('max_from_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_pairs', to='crypto.cryptocurrency')),
                ('to_crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_pairs', to='crypto.cryptocurrency')),
            ],
            options={
                'verbose_name': 'exchange pair',
                'verbose_name_plural': 'exchange pairs',
                'unique_together': {('from_crypto', 'to_crypto')},
            },
        ),
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto.cryptocurrency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user wallet',
                'verbose_name_plural': 'user wallets',
                'unique_together': {('user', 'crypto')},
            },
        ),
    ]
