# Generated by Django 5.2.1 on 2025-06-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='symbol',
            field=models.CharField(max_length=20, verbose_name='Symbol'),
        ),
        migrations.AlterUniqueTogether(
            name='cryptocurrency',
            unique_together={('symbol', 'network')},
        ),
    ]
