# Generated by Django 5.0.6 on 2025-05-28 05:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userwallet',
            name='available_balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=24),
        ),
        migrations.AddField(
            model_name='userwallet',
            name='locked_balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=24),
        ),
        migrations.CreateModel(
            name='CardDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('currency', models.CharField(default='RUB', max_length=3, verbose_name='Currency')),
                ('card_last4', models.CharField(blank=True, max_length=4, null=True, verbose_name='Last 4 digits')),
                ('card_brand', models.CharField(blank=True, max_length=20, null=True, verbose_name='Card Brand')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Payment ID')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Fee')),
                ('crypto_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True, verbose_name='Crypto Amount')),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True, verbose_name='Exchange Rate')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_deposits', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_deposits', to='crypto.userwallet')),
            ],
            options={
                'verbose_name': 'card deposit',
                'verbose_name_plural': 'card deposits',
            },
        ),
        migrations.CreateModel(
            name='InvestmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Interest Rate (%)')),
                ('duration_value', models.PositiveIntegerField(default=1, verbose_name='Duration Value')),
                ('duration_unit', models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], default='month', max_length=10, verbose_name='Duration Unit')),
                ('min_investment', models.DecimalField(decimal_places=8, max_digits=18, verbose_name='Minimum Investment')),
                ('max_investment', models.DecimalField(decimal_places=8, max_digits=18, verbose_name='Maximum Investment')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('early_withdrawal_allowed', models.BooleanField(default=False, verbose_name='Early Withdrawal Allowed')),
                ('early_withdrawal_fee', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Early Withdrawal Fee (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_plans', to='crypto.cryptocurrency')),
            ],
            options={
                'verbose_name': 'investment plan',
                'verbose_name_plural': 'investment plans',
            },
        ),
        migrations.CreateModel(
            name='UserInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=24, verbose_name='Investment Amount')),
                ('expected_return', models.DecimalField(decimal_places=8, max_digits=24, verbose_name='Expected Return')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('withdrawn', 'Withdrawn Early')], default='active', max_length=20, verbose_name='Status')),
                ('actual_return', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True, verbose_name='Actual Return')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='Completion Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_investments', to='crypto.investmentplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='crypto.userwallet')),
            ],
            options={
                'verbose_name': 'user investment',
                'verbose_name_plural': 'user investments',
            },
        ),
    ]
