# Generated by Django 5.0.6 on 2025-06-02 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_userwallet_available_balance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userwallet',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userwallet',
            name='crypto',
        ),
        migrations.RemoveField(
            model_name='userwallet',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userinvestment',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='carddeposit',
            name='wallet',
        ),
        migrations.CreateModel(
            name='SystemWalletAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, unique=True, verbose_name='Deposit Address')),
                ('crypto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='system_address', to='crypto.cryptocurrency', verbose_name='Cryptocurrency')),
            ],
            options={
                'verbose_name': 'system wallet address',
                'verbose_name_plural': 'system wallet addresses',
            },
        ),
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=8, default=0, max_digits=24, verbose_name='Balance')),
                ('crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_balances', to='crypto.cryptocurrency', verbose_name='Cryptocurrency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'user balance',
                'verbose_name_plural': 'user balances',
            },
        ),
        migrations.AddField(
            model_name='carddeposit',
            name='balance_entry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='card_deposits', to='crypto.userbalance', verbose_name='User Balance Entry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinvestment',
            name='balance_entry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='crypto.userbalance', verbose_name='User Balance Entry'),
            preserve_default=False,
        ),
    ]
