# Generated by Django 5.0.6 on 2025-06-02 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0003_alter_userwallet_unique_together_and_more'),
        ('transactions', '0004_remove_deposit_wallet_remove_withdrawal_wallet_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserWallet',
        ),
        migrations.AlterUniqueTogether(
            name='userbalance',
            unique_together={('user', 'crypto')},
        ),
    ]
