# Generated by Django 5.2.1 on 2025-06-18 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0003_userbalance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userwallet',
            name='encrypted_private_key',
            field=models.TextField(blank=True, null=True, verbose_name='Encrypted Private Key'),
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=28)),
                ('tx_hash', models.CharField(blank=True, max_length=128, null=True, verbose_name='Blockchain Tx Hash')),
                ('type', models.CharField(choices=[('in', 'Deposit'), ('out', 'Withdrawal')], max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='crypto.cryptocurrency')),
                ('system_wallet', models.ForeignKey(blank=True, help_text='System wallet that was used for this transfer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='crypto.userwallet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'transfer',
                'verbose_name_plural': 'transfers',
                'ordering': ['-created_at'],
            },
        ),
    ]
