# Generated by Django 5.2.1 on 2025-06-18 08:02

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0004_userwallet_encrypted_private_key_transfer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_amount', models.DecimalField(decimal_places=8, max_digits=28)),
                ('to_amount', models.DecimalField(decimal_places=8, max_digits=28)),
                ('rate', models.DecimalField(decimal_places=12, help_text='Exchange rate applied', max_digits=28)),
                ('fee_percent', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Fee percent taken', max_digits=6)),
                ('fee_amount', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=28)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('executed', 'Executed'), ('canceled', 'Canceled'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_orders_from', to='crypto.cryptocurrency')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_orders_to', to='crypto.cryptocurrency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'exchange order',
                'verbose_name_plural': 'exchange orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
