# Generated by Django 5.0.6 on 2025-06-03 12:04

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0004_delete_userwallet_alter_userbalance_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userbalance',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userbalance',
            name='crypto',
        ),
        migrations.RemoveField(
            model_name='userbalance',
            name='user',
        ),
        migrations.RemoveField(
            model_name='carddeposit',
            name='balance_entry',
        ),
        migrations.RemoveField(
            model_name='userinvestment',
            name='balance_entry',
        ),
        migrations.AlterModelOptions(
            name='cryptocurrency',
            options={'ordering': ['name'], 'verbose_name': 'currency', 'verbose_name_plural': 'currencies'},
        ),
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='api_id',
        ),
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='fee_percentage',
        ),
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='max_amount',
        ),
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='min_amount',
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='currency_type',
            field=models.CharField(choices=[('fiat', 'Fiat'), ('crypto', 'Cryptocurrency')], default='crypto', max_length=10, verbose_name='Currency Type'),
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='max_exchange_amount',
            field=models.DecimalField(decimal_places=8, default=Decimal('10.0'), max_digits=18, verbose_name='Max Exchange Amount'),
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='min_exchange_amount',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.0001'), max_digits=18, verbose_name='Min Exchange Amount'),
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='network',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Network'),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='coingecko_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CoinGecko ID'),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='crypto_icons/', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='symbol',
            field=models.CharField(max_length=20, unique=True, verbose_name='Symbol'),
        ),
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=24, verbose_name='Total Balance')),
                ('available_balance', models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=24, verbose_name='Available Balance')),
                ('locked_balance', models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=24, verbose_name='Locked Balance')),
                ('is_system_wallet', models.BooleanField(default=False, verbose_name='System Wallet')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto.cryptocurrency', verbose_name='Currency')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'wallet',
                'verbose_name_plural': 'wallets',
            },
        ),
        migrations.AddField(
            model_name='carddeposit',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_deposits', to='crypto.userwallet'),
        ),
        migrations.AddField(
            model_name='userinvestment',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='crypto.userwallet'),
        ),
        migrations.DeleteModel(
            name='SystemWalletAddress',
        ),
    ]
