# Generated by Django 5.0.6 on 2025-06-03 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0005_alter_userbalance_unique_together_and_more'),
        ('transactions', '0007_remove_deposit_balance_entry_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserBalance',
        ),
        migrations.AlterUniqueTogether(
            name='userwallet',
            unique_together={('user', 'currency', 'is_system_wallet')},
        ),
    ]
