# Generated by Django 5.2.1 on 2025-06-19 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0005_exchangeorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinvestment',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='system_wallet',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='userbalance',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userbalance',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='userbalance',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userinvestment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userinvestment',
            name='wallet',
        ),
        migrations.AlterModelOptions(
            name='blockchainstate',
            options={},
        ),
        migrations.DeleteModel(
            name='InvestmentPlan',
        ),
        migrations.DeleteModel(
            name='Transfer',
        ),
        migrations.DeleteModel(
            name='UserBalance',
        ),
        migrations.DeleteModel(
            name='UserInvestment',
        ),
    ]
