# Generated by Django 5.2.1 on 2025-06-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0006_remove_userinvestment_plan_remove_transfer_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemwalletaddress',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Address'),
        ),
    ]
