# Generated by Django 5.0.6 on 2025-06-13 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0006_delete_userbalance_alter_userwallet_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemWalletAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=50, verbose_name='Network')),
                ('address', models.CharField(max_length=255, unique=True, verbose_name='Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_addresses', to='crypto.cryptocurrency')),
            ],
            options={
                'verbose_name': 'System Wallet Address',
                'verbose_name_plural': 'System Wallet Addresses',
                'unique_together': {('currency', 'network')},
            },
        ),
        migrations.CreateModel(
            name='UserDepositMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=50, verbose_name='Network')),
                ('memo', models.CharField(max_length=128, unique=True, verbose_name='Memo/Destination Tag')),
                ('status', models.CharField(choices=[('waiting', 'Waiting for deposit'), ('used', 'Used'), ('expired', 'Expired')], db_index=True, default='waiting', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto.cryptocurrency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_memos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Deposit Memo',
                'verbose_name_plural': 'User Deposit Memos',
            },
        ),
        migrations.DeleteModel(
            name='CardDeposit',
        ),
    ]
