# Generated by Django 5.0.6 on 2025-06-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0007_systemwalletaddress_userdepositmemo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainState',
            fields=[
                ('blockchain', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Blockchain/Network')),
                ('last_processed_block', models.BigIntegerField(default=0, verbose_name='Last Processed Block')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blockchain Scanner State',
                'verbose_name_plural': 'Blockchain Scanner States',
            },
        ),
    ]
