# Generated by Django 5.0.6 on 2025-06-20 15:00

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0007_alter_systemwalletaddress_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=24, verbose_name='Commission Balance')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_wallets', to='crypto.cryptocurrency', verbose_name='Currency')),
            ],
            options={
                'verbose_name': 'commission wallet',
                'verbose_name_plural': 'commission wallets',
                'unique_together': {('currency',)},
            },
        ),
    ]
