# Generated by Django 5.0.6 on 2025-06-20 15:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0008_commissionwallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='fee_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.2'), help_text='Default platform commission in percent (0-100)', max_digits=5, verbose_name='Platform Fee Percentage'),
        ),
    ]
