# Generated by Django 5.2.1 on 2025-06-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0008_blockchainstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='contract_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contract Address'),
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='decimals',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Decimals'),
        ),
    ]
