# Generated by Django 5.2.1 on 2025-06-20 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0009_cryptocurrency_fee_percentage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=24)),
                ('commission_type', models.CharField(choices=[('exchange', 'Обмен'), ('withdraw', 'Вывод')], max_length=16)),
                ('related_object_id', models.CharField(blank=True, help_text='ID связанной операции (например, ExchangeOrder или Withdrawal)', max_length=64, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto.cryptocurrency')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'commission transaction',
                'verbose_name_plural': 'commission transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
