# Generated by Django 5.2.3 on 2025-07-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0010_commissiontransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='requires_memo',
            field=models.BooleanField(default=False, help_text='Check if this currency requires a Memo/Destination Tag for deposits.', verbose_name='Requires Memo'),
        ),
    ]
