# Generated by Django 5.2.3 on 2025-07-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0011_cryptocurrency_requires_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwallet',
            name='deposit_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Deposit Address'),
        ),
    ]
