# Generated by Django 5.2.3 on 2025-09-22 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0012_userwallet_deposit_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Wallet Address')),
                ('encrypted_private_key', models.TextField(verbose_name='Encrypted Private Key')),
                ('network', models.CharField(max_length=50, verbose_name='Network')),
                ('wallet_type', models.CharField(choices=[('user', 'User Wallet'), ('system', 'System Wallet'), ('test', 'Test Wallet')], default='user', max_length=10, verbose_name='Wallet Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('created_by', models.CharField(blank=True, max_length=100, verbose_name='Created By')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto.cryptocurrency', verbose_name='Currency')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Generated Wallet',
                'verbose_name_plural': 'Generated Wallets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['address'], name='crypto_gene_address_1e3439_idx'), models.Index(fields=['currency', 'network'], name='crypto_gene_currenc_a79ae8_idx'), models.Index(fields=['user', 'wallet_type'], name='crypto_gene_user_id_dc5e46_idx'), models.Index(fields=['created_at'], name='crypto_gene_created_a532bf_idx')],
            },
        ),
    ]
