# Generated by Django 5.2.3 on 2025-10-16 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0013_add_generated_wallet_model'),
        ('transactions', '0012_auto_20250921_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissiontransaction',
            name='commission_type',
            field=models.CharField(choices=[('exchange', 'Обмен'), ('withdraw', 'Вывод'), ('consolidation', 'Консолидация')], max_length=16),
        ),
        migrations.CreateModel(
            name='SystemWalletBalanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_address', models.CharField(max_length=255, verbose_name='System Address')),
                ('blockchain_balance', models.DecimalField(decimal_places=8, max_digits=24, verbose_name='Blockchain Balance')),
                ('database_balance', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True, verbose_name='Database Balance')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('consolidation', 'Consolidation'), ('withdrawal', 'Withdrawal'), ('manual_check', 'Manual Check'), ('system_update', 'System Update')], max_length=20, verbose_name='Transaction Type')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto.cryptocurrency', verbose_name='Currency')),
                ('related_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.transaction', verbose_name='Related Transaction')),
            ],
            options={
                'verbose_name': 'System Wallet Balance Log',
                'verbose_name_plural': 'System Wallet Balance Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['currency', 'created_at'], name='crypto_syst_currenc_937669_idx'), models.Index(fields=['transaction_type', 'created_at'], name='crypto_syst_transac_855303_idx'), models.Index(fields=['system_address'], name='crypto_syst_system__4f25a1_idx')],
            },
        ),
    ]
