services:
  postgres:
    container_name: cryptoobmen-postgres
    restart: always
    image: postgres:17.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../../backend/.env.backend
    ports:
      - "5432:5432"  # Открываем порт наружу для доступа
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cryptoobmen_network


networks:
  cryptoobmen_network:
    name: cryptoobmen_network
    driver: bridge

volumes:
  postgres_data:
    name: cryptoobmen_postgres_data  # Именованный том для сохранения данных