services:
  postgres:
    container_name: cryptoobmen-postgres
    restart: always
    image: postgres:17.4
    volumes:
      - ./postgres/data/:/var/lib/postgresql/data/
    env_file:
      - ./postgres/.env
    ports:
      - 5432:5432
  redis:
    container_name: cryptoobmen-redis
    restart: always
    image: redis:7.4.3
    expose:
      - 6379
  backend:
    container_name: cryptoobmen-backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/app/
    env_file:
      - ./backend/.env
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis
  frontend:
    container_name: cryptoobmen-frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - ./frontend/:/usr/src/app/
      - /usr/src/app/node_modules/
    env_file:
      - ./frontend/.env
    ports:
      - 3000:3000
    depends_on:
      - backend
