services:
  # Nginx сервис для Cryptoobmen
  nginx:
    build:
      context: ./docker/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/scripts:/usr/local/bin
      - ./static:/usr/share/nginx/static
      - ./media:/usr/share/nginx/media
      - ./docker/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - crypto-backend
      - crypto-frontend
    restart: always
    networks:
      - cryptoobmen_network
    command: nginx -g 'daemon off;'

  # Бэкенд Cryptoobmen
  crypto-backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    volumes:
      - ./backend:/app
      - ./static:/app/static
      - ./media:/app/media
    environment:
      - DEBUG=0
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    env_file:
      - ./docker/backend/.env.prod
    restart: always
    networks:
      - cryptoobmen_network
    external_links:
      - cryptoobmen-postgres:postgres
      - cryptoobmen-redis:redis

  # Фронтенд Cryptoobmen
  crypto-frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    # В продакшене не монтируем исходники, используем только собранные файлы
    environment:
      - NODE_ENV=production
    env_file:
      - ./frontend/.env.production
    restart: always
    networks:
      - cryptoobmen_network

networks:
  cryptoobmen_network:
    name: cryptoobmen_network
    driver: bridge
    external: true 