services:

  redis:
    image: redis:7-alpine
    container_name: docker-redis-1
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data
    networks:
      - cryptoobmen_network

  backend:
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile
    env_file:
      - ../backend/.env.backend
    volumes:
      - ../backend:/app
      - ./backend/entrypoint.sh:/app/entrypoint.sh   
    ports:
      - "8000:8000"
    command: uvicorn core.asgi:application --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - redis
    networks:
      - default
      - cryptoobmen_network

  worker:
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile
    env_file:
      - ../backend/.env.backend
    
    volumes:
      - ../backend:/app
      - ./backend/entrypoint.sh:/app/entrypoint.sh
    depends_on:
      - backend
      - redis
    command: celery -A core worker -l info --pool=solo
    networks:
      - default
      - cryptoobmen_network

  beat:
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile
    env_file:
      - ../backend/.env.backend
  
    volumes:
      - ../backend:/app
      - ./backend/entrypoint.sh:/app/entrypoint.sh
    depends_on:
      - backend
      - redis
    command: celery -A core beat -l info
    networks:
      - default
      - cryptoobmen_network

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend/Dockerfile
      args:
        BUILD_ENV: development
    env_file:
      - ../frontend/.env.development
    environment:
      - NODE_ENV=development
      - NODE_OPTIONS=--max-old-space-size=4096
    volumes:
      - ../frontend:/app
      - /app/.next
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: npm run dev
    networks:
      - default
      - cryptoobmen_network

networks:
  default:
  cryptoobmen_network:
    external: true


volumes:
  redis_data:
    name: cryptoobmen_redis_data
