# Generated by Django 5.2.1 on 2025-07-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='refunded',
            field=models.BooleanField(default=False),
        ),
    ]
