# Generated by Django 5.0.6 on 2025-04-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='verified',
            new_name='is_verified',
        ),
        migrations.RemoveField(
            model_name='review',
            name='text',
        ),
        migrations.AddField(
            model_name='review',
            name='content',
            field=models.TextField(default='', verbose_name='Review Content'),
        ),
        migrations.AddField(
            model_name='review',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Featured'),
        ),
    ]
