# Generated by Django 5.0.6 on 2025-06-02 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0003_alter_userwallet_unique_together_and_more'),
        ('transactions', '0003_rename_verified_review_is_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='wallet',
        ),
        migrations.AddField(
            model_name='deposit',
            name='balance_entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='crypto.userbalance'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='balance_entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='crypto.userbalance'),
        ),
    ]
