# Generated by Django 5.0.6 on 2025-06-02 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0004_delete_userwallet_alter_userbalance_unique_together'),
        ('transactions', '0004_remove_deposit_wallet_remove_withdrawal_wallet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='balance_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='crypto.userbalance'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='balance_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='crypto.userbalance'),
        ),
    ]
