# Generated by Django 5.2.3 on 2025-07-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='memo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='MEMO/Tag'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('processing', 'В обработке'), ('completed', 'Завершено'), ('failed', 'Ошибка'), ('cancelled', 'Отменено'), ('refunded', 'Возвращено')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'Депозит'), ('withdrawal', 'Вывод'), ('exchange', 'Обмен'), ('transfer', 'Перевод'), ('fee', 'Комиссия')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('success', 'Успешно'), ('failed', 'Ошибка')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='type',
            field=models.CharField(choices=[('in', 'Входящий'), ('out', 'Исходящий')], max_length=3),
        ),
    ]
