# Generated by Django 5.0.6 on 2025-06-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_deposit_balance_entry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
