# Generated by Django 5.2.3 on 2025-07-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_withdrawal_memo_alter_transaction_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='email_confirmation_token',
            field=models.UUIDField(blank=True, null=True, verbose_name='Email Confirmation Token'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='email_confirmation_token_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Email Token Expires At'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('awaiting_confirmation', 'Ожидает подтверждения'), ('processing', 'В обработке'), ('completed', 'Завершено'), ('failed', 'Ошибка'), ('cancelled', 'Отменено'), ('refunded', 'Возвращено')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='is_2fa_confirmed',
            field=models.BooleanField(default=False, verbose_name='2FA Confirmed'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='is_email_confirmed',
            field=models.BooleanField(default=False, verbose_name='Email Confirmed'),
        ),
    ]
