# Generated by Django 5.0.6 on 2025-06-03 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0005_alter_userbalance_unique_together_and_more'),
        ('transactions', '0006_alter_deposit_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='balance_entry',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='balance_entry',
        ),
        migrations.AddField(
            model_name='deposit',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='crypto.userwallet'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='crypto.userwallet'),
        ),
    ]
