# Generated by Django 5.2.3 on 2025-07-31 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_withdrawal_email_confirmation_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='withdrawal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer', to='transactions.withdrawal'),
        ),
    ]
