# Generated by Django 5.2.3 on 2025-08-02 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_transfer_withdrawal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawal',
            name='is_2fa_confirmed',
        ),
    ]
