# Generated by Django 5.2.3 on 2025-09-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_remove_withdrawal_is_2fa_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'Депозит'), ('withdrawal', 'Вывод'), ('exchange', 'Обмен'), ('transfer', 'Перевод'), ('fee', 'Комиссия'), ('consolidation', 'Консолидация')], max_length=20),
        ),
    ]
