# Generated by Django 5.2.3 on 2025-09-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_alter_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tx_hash',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
