# Generated by Django 5.2.3 on 2025-09-21 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_add_unique_tx_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='deposit_address',
            field=models.CharField(blank=True, help_text='Адрес, на который был получен депозит', max_length=255, null=True),
        ),
    ]
