# Generated by Django 5.2.3 on 2025-09-21 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_transaction_deposit_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='deposit_address',
        ),
    ]
